#!/usr/bin/env bash
# This script is for displaying "Best School"  10 times but at the 9th iteration, it prints "Hi"

w=0
while [ "$w" -lt 10 ]; do
    if [ "$w" -eq 9 ]; then
        echo "Hi"
    fi
    ((w+=1))
    echo "Best School"
done