#!/usr/bin/env bash
# This script is for displaying "Best School"  10 times but at the 9th iteration, it prints "Hi"

w=1

while [ "$w" -le 20 ]; do
    case "$w" in
        4) echo "bad luck from China" ;;
        9) echo "bad luck from Japan" ;;
        17) echo "bad luck from Italy" ;;
        *) echo $w ;;
    esac
    ((w+=1))
done